// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-central-1',
  aws_appsync_graphqlEndpoint:
    'https://6porbqtej5fgznpmlcwesi7cci.appsync-api.eu-central-1.amazonaws.com/graphql',
  aws_appsync_region: 'eu-central-1',
  aws_content_delivery_bucket: 'wellenreiterapp.com',
  aws_content_delivery_bucket_region: 'eu-central-1',
  aws_content_delivery_url:
    'http://wellenreiterapp.com.s3-website.eu-central-1.amazonaws.com'
};

export default awsmobile;
